# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Compile with Gradle
      run: ./gradlew compileJava
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with: 
        name: buildJar
        path: build
  
  test:
    needs: compile
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: buildJar
        path: build/
    - name: Run test with Gradle
      run: ./gradlew test
      continue-on-error: true
    - name: Upload artifact (test report)
      uses: actions/upload-artifact@v2
      with: 
        name: testReport
        path: build/reports/tests/
        
  assemble:
    needs: [compile, test]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: buildJar
        path: build/
    - name: Assemble with Gradle
      run: ./gradlew assemble
      
  release:
    if: ${{ github.ref == 'ref/heads/main' }}
    needs: [compile, test, assemble]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
